language: node_js

sudo: false

node_js:
- '6'

git:
  depth: 10

branches:
  only:
  - master

script:
  - npm run test

after_success:
  - npm run docs

deploy:
- provider: pages
  edge: true
  github_token: ${GITHUB_TOKEN}
  local_dir: docs
  skip_cleanup: true
